### ISSUE TITLE
Bug: fs-extra write issue - Workaround Patch Implementation?

### ISSUE THREAD

**Issue by CatWithCode** [signalflatpak/signal#25]
**Describe the problem**
fs-extra has issues on arm64:
This is in my app.log:
`{"level":50,"time":"2024-11-09T15:06:52.865Z","msg":"reencryptAttachmentV2(downloadAttachment/[REDACTED]C0=): Failed to decrypt attachment Error: reencryptAttachmentV2(downloadAttachment/[REDACTED]C0=): Failed to create write path\n    at decryptAndReencryptLocally ([REDACTED]/resources/app.asar/preload.bundle.js:106326:13)\n    at async Object.downloadAttachment [as downloadAttachmentFromServer] ([REDACTED]/resources/app.asar/preload.bundle.js:153132:16)\n    at async Object.downloadAttachment ([REDACTED]/resources/app.asar/preload.bundle.js:153333:12)\n    at async runDownloadAttachmentJobInner ([REDACTED]/resources/app.asar/preload.bundle.js:153795:24)\n    at async Object.runDownloadAttachmentJob ([REDACTED]/resources/app.asar/preload.bundle.js:153670:20)\n    at async _AttachmentDownloadManager.startJob ([REDACTED]/resources/app.asar/preload.bundle.js:129331:26)\nCaused by: Error: EFAULT: bad address in system call argument, write"}`

The result it that images do not load. This seems to be easy to fix.
Dennis Ameling seems to have created a simple patch:

[https://github.com/dennisameling/signal-desktop-automation](https://github.com/dennisameling/signal-desktop-automation)

[https://github.com/signalapp/Signal-Desktop/issues/6744#issuecomment-2398994786](https://github.com/signalapp/Signal-Desktop/issues/6744#issuecomment-2398994786)

I tryed to fork this repo and try to apply myself but I never worked with GitHub Build piplines.

Could this be integrated? 
As far as i can see it just trys writing anyway and if it errors out it then skips it?

**Screenshots**

**System Details**
 - Signal version: refs/tags/7.31.0
 - OS: Ubuntu Touch focal
 - Desktop: Ubuntu Touch Mir - Libertine
 - Packaging type:
    - [x] .deb file
 - Platform:
    - [x] arm64

**Comment by adamthiede** [comment]
Thanks for the bug report. Unfortunately we are not building the .deb package anymore in this repository. Does your platform support flatpak?

**Comment by CatWithCode** [comment]
No. Flatpack dose not work on my platform.
Is there a reason no longer building a deb? Dependencie issues or other reasons?

**Comment by adamthiede** [comment]
The .deb was just something we happened to be producing and it was never the real "target" of this repository.

Sorry about this. [This repository](https://gitlab.com/undef1/signal-desktop-builder/-/packages) still produces .deb builds though!

**Comment by bellegarde-c** [comment]
Has it been fixed ? Here, using flatpak package, images are not loaded.

Works with https://github.com/dennisameling/Signal-Desktop
