### ISSUE TITLE
Unhandled libringrtc-arm64.node: undefined symbol: pulse_rust_init error after upgrading to 7.33.0

### ISSUE THREAD

**Issue by englut** [signalflatpak/signal#26]
**Describe the problem**
I've updated to the latest version of Signal via the repo and now Signal throws the following error.
I tried reinstalling with the bundle and from the repo. Along with installing the older version (7.32.0), which I had thought would work. I'm not sure why it's not working now either. Maybe there's some kind of config corruption.

```
❯ flatpak run org.signal.Signal
Debug: Will run signal with the following arguments: --ozone-platform-hint=auto
Debug: Additionally, user gave:
Set Windows Application User Model ID (AUMID) { AUMID: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /app/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME XXXXXXX
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/XXXXXX/.var/app/org.signal.Signal/config/Signal
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
making app single instance
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings

(signal-desktop:2): Gtk-WARNING **: 00:36:31.762: Theme parsing error: main-dark.css:2470:0: Expected a valid selector

(signal-desktop:2): Gtk-WARNING **: 00:36:31.867: Theme parsing error: main-dark.css:2470:0: Expected a valid selector
Unhandled Error: Error: /app/Signal/resources/app.asar.unpacked/node_modules/@signalapp/ringrtc/build/linux/libringrtc-arm64.node: undefined symbol: pulse_rust_init
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/app/Signal/resources/app.asar/node_modules/@signalapp/ringrtc/dist/ringrtc/Native.js:33:19)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
```

**Screenshots**

**System Details**
 - Signal version: 7.33.0
 - OS: Fedora 41 Asahi Linux Remix
 - Desktop: KDE Plasma 6.2.3
 - Packaging type:
    - [x] Flatpak from repo
    - [x] Flatpak bundle 
 - Platform:
    - [x] arm64

**Comment by adamthiede** [comment]
Thanks, I am observing the same problem. Looking into it.

**Comment by adamthiede** [comment]
Installing the bundle from the 7.32 release should be a workaround. If for some reason that doesn't work, try removing the app data at `.var/app/org.signal.Signal` and launch it again.

**Comment by adamthiede** [comment]
added potential workaround; as soon as [this](https://github.com/signalflatpak/signal/actions/runs/11836913922) builds it'll be available for testing. https://github.com/signalflatpak/signal/commit/18d8086f186ed77ef5bbea06560d5b53c512d8e3

**Comment by englut** [comment]
Amazing. I was wondering if it had something to do with ringrtc, but didn't dive as deeply as I should have! Thanks for the quick release with the previously working version :pray:
